# Tarea día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [50]:
import numpy as np
import random

In [4]:
a = np.zeros([10, 10])
a
#Forma de crear matriz de ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
c= np.random.randint(2, size=(10,10))
print(c)
print(c.sum())
#Se genero aleatoriamente una matriz que rellene con números enteros con rango (2), es decir, solo genera el uno y el 
#cero. Con la función suma, se verificó que la matriz en general sumará 50 (de no ser así, se repite el proceso hasta
#que de 50, es decir, cuando la mitad de los elementos sean 1)

[[0 1 0 0 1 0 0 0 1 1]
 [0 1 1 0 0 1 1 1 0 1]
 [0 1 1 1 0 1 0 0 0 0]
 [1 1 1 0 1 0 1 0 0 0]
 [1 1 1 0 0 1 0 0 0 0]
 [0 1 1 0 1 1 0 0 0 1]
 [1 0 1 0 1 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 0 1]
 [0 1 1 1 1 0 0 1 1 0]
 [0 0 1 1 1 1 0 0 1 1]]
50


In [24]:
mat_random = c.copy()
print(mat_random) #Con esta nueva variable nos aseguramos que sea una matriz de ceros, rellena aleatoreamente 
#con 50 elementos equivalentes a 1

[[0 1 0 0 1 0 0 0 1 1]
 [0 1 1 0 0 1 1 1 0 1]
 [0 1 1 1 0 1 0 0 0 0]
 [1 1 1 0 1 0 1 0 0 0]
 [1 1 1 0 0 1 0 0 0 0]
 [0 1 1 0 1 1 0 0 0 1]
 [1 0 1 0 1 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 0 1]
 [0 1 1 1 1 0 0 1 1 0]
 [0 0 1 1 1 1 0 0 1 1]]


In [96]:
d = np.random.choice(2, size=(10,10), replace = True, p=[0.5, 0.5])
print(d)
print(d.sum())

[[0 0 0 1 1 1 1 1 0 1]
 [0 0 1 0 1 1 0 0 0 1]
 [0 0 0 1 1 1 0 1 0 1]
 [0 0 1 0 1 0 1 1 0 0]
 [1 1 1 0 1 1 1 0 1 0]
 [0 1 1 0 1 1 0 0 1 0]
 [0 1 0 0 1 0 1 1 1 1]
 [0 1 0 0 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 1 1 0 0 0 1]]
50


### Otro método

In [203]:
a = np.zeros([100]) #Se crea una fila con 100 ceros
b = np.arange(100) #Crea una fila que va con números de 0 al 99
c = np.random.choice(b, int(50), replace = False) #Variable que posee aleatoriamente 50 números enteros entre 0 a 100

print(a)
print(c)
a[c]=1 #Con esta instrucción se sustituye la posición de "c" en "a" y lo remplaza por un uno
print(a)
a.resize(10,10) #Establece la matriz a en dimensiones de 10 x 10
print(a)
print("La sumatoria es de: ", a.sum())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[76  2 58 53 21  1 29 55 26 43 10 77  7 49  0 15 37 48 82 25 11 91 65 39
 80 38 99 14 56 27 73 93 13 78 41 51 54 50 59 47  6 52 67 34  3 72 57 61
 74 92]
[1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 1.]
[[1. 1. 1. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



#### Inciso 1

In [25]:
a = np.zeros([5,2])
print(a) #Matriz de ceros

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
b = np.ones([5,2])
print(b) #Matriz de unos.

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
np.column_stack((a))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [103]:
ca= np.concatenate(a)
np.vstack(ca)
da = np.vstack(ca)#La variable da representa un vector columna lleno de 0
print(da)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [102]:
cb = np.concatenate(b)
np.vstack(cb)
db = np.vstack(cb) #La variable db representa un vector columna lleno de 1
print(db)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


#### Inciso b

In [104]:
da[:, None]
print(da[:, None]) #Con el comando [:, None] se añadió una dimensión adicional

[[[0.]]

 [[0.]]

 [[0.]]

 [[0.]]

 [[0.]]

 [[0.]]

 [[0.]]

 [[0.]]

 [[0.]]

 [[0.]]]


In [105]:
db[:, None]
print(db[:, None]) #Con el comando [:, None] se añadió una dimensión adicional

[[[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]]


#### Inciso c

In [112]:
a = np.zeros([5,2])
print(a) #Matriz de ceros
b = np.ones([5,2])
print(b) #Matriz de unos.
c= np.hstack(a)
d= np.hstack(b)
print(c)
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [120]:
e=np.concatenate((c,d)) #Se creó la variable e, la cual concatena las matrices a y b
print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [121]:
e.resize(20,1) #Con el comando "resize" se volvió en vertical la matriz e
print(e)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [142]:
x= np.random.randint(10, size=(5,3)) #La variable x genera números aleatorios
print(x)

[[3 4 3]
 [9 6 8]
 [1 2 4]
 [6 3 5]
 [9 8 3]]


In [143]:
def f(x,y,z):
    return 2*x + 3*y + z**2

z=f(x[:,0], x[:,1], x[:,2]) #Dentro de la función se ingresaron las columnas de la matriz X como variables. 
#Se definió la variable z, como la matriz que recibe los resultados de la función f(x,y,z), la cual se encuentra arriba.
print(np.vstack(z))



[[ 27]
 [100]
 [ 24]
 [ 46]
 [ 51]]


## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

### Montecarlo con el cuadrado en la esquina

In [445]:
monte=np.random.randint(0,2, (50,50)) #Permite generar un cuadrado con un área de 50*50
proporcion=np.count_nonzero(monte ==1)
areagrande=50*50
proporcion
print("El cuadrado a analizar es: ")
print(monte)
peque=monte[0:20,0:20]
print("La matriz de 20*20 es: ")
print(peque)
cuadradopeque=peque.sum()#Recopila la sumatoria del cuadrado de proporciones de 20*20 en la esquina de la matriz
print("El total de unos dentro del cuadrado de 20*20 es de: ",cuadradopeque)
areapequeña=(cuadradopeque*areagrande)/proporcion
print("El área del cuadrado pequeño es de: ", areapequeña)
#Como el valor se aproxima a 400 se puede concluir que esta calculando bien el área.

El cuadrado a analizar es: 
[[0 1 1 ... 1 1 1]
 [1 0 0 ... 0 1 1]
 [0 0 0 ... 1 1 1]
 ...
 [1 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 1 1 1]]
La matriz de 20*20 es: 
[[0 1 1 1 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1]
 [1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 1]
 [0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0]
 [0 1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0]
 [0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 0 1]
 [1 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 1 1]
 [0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 0 1 1 0 0]
 [0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 1]
 [1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1]
 [1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 0 1 0]
 [0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0]
 [0 1 1 1 1 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1]
 [0 0 0 1 1 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0]
 [1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1]
 [0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 0 1 0 1 0 0 1 0 1 1 1 1 0 1 1]
 [1 0 0 0 0

### Montecarlo con el cuadrado en el centro

In [444]:
monte=np.random.randint(0,2, (50,50)) #Permite generar un cuadrado con un área de 50*50
proporcion=np.count_nonzero(monte ==1)
areagrande=50*50
proporcion
print("El cuadrado a analizar es: ")
print(monte)
peque=monte[15:35,15:35]
print("La matriz de 20*20 es: ")
print(peque)
cuadradopeque=peque.sum()#Recopila la sumatoria del cuadrado de proporciones de 20*20 en el centro de la matriz
print("El total de unos dentro del cuadrado de 20*20 es de: ",cuadradopeque)
areapequeña=(cuadradopeque*areagrande)/proporcion
print("El área del cuadrado pequeño es de: ", areapequeña)
#Como el valor se aproxima a 400 se puede concluir que esta calculando bien el área.

El cuadrado a analizar es: 
[[1 1 1 ... 1 0 0]
 [1 0 1 ... 0 1 1]
 [1 1 1 ... 0 0 1]
 ...
 [1 1 0 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 [0 1 1 ... 0 0 1]]
La matriz de 20*20 es: 
[[1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 1]
 [1 1 0 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0]
 [1 0 1 0 0 0 1 1 1 0 1 0 0 1 1 1 0 0 0 1]
 [1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 0]
 [1 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1]
 [0 0 1 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1]
 [1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1]
 [0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0]
 [1 0 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 1 1 0]
 [0 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0]
 [1 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1]
 [1 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0]
 [0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1]
 [1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0]
 [1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 1 1]
 [1 0 1 0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 1]
 [0 1 1 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 1]
 [1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 0 1]
 [0 1 0 0 1

***
# *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

## Tarea, inciso 1
1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)

##### Funciones Array creation routines

In [144]:
#Función 1: Empty
#Return a new array of given shape and type, without initializing entries.

print(np.empty([3, 3], dtype=int))
        
print(np.empty([2, 2], dtype=float))






[[         1          0          0]
 [         0  645922816          0]
 [1245708288        116 -451866752]]
[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 2.46151512e-312]]


In [145]:
#Función 2: Empty like
#Return a new array with the same shape and type as a given array.

a = ([10,20,30], [7,8,6])                         
np.empty_like(a)


array([[ -485059456,         402,           0],
       [          0,      131074, -2147483648]])

In [146]:
#Función 3: eye
#Return a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(4, dtype=int)



array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [147]:
#Función 4: arange
#Return evenly spaced values within a given interval.
print(np.arange(5))
print(np.arange(4,11))
print(np.arange(2,9,2))


[0 1 2 3 4]
[ 4  5  6  7  8  9 10]
[2 4 6 8]


In [149]:
#Función 5: tri
print(np.tri(4, 5, -2))
print(np.tri(4, 5, 2))


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [150]:
#Función 6: Tril
#Lower triangle of an array. Return a copy of an array with elements above the k-th diagonal zeroed.

np.tril([[1,2,3],[1,2,3],[1,2,3],[1,2,3]], -1)


array([[0, 0, 0],
       [1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [152]:
#Función 7: vander
#Generate a Vandermonde matrix. The columns of the output matrix are powers of the input vector. 
#The order of the powers is determined by the increasing boolean argument. 
#Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power 
#of N - i - 1. Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

x = np.array([3, 4, 5, 5])
N = 5
np.vander(x, N)


array([[ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1],
       [625, 125,  25,   5,   1]])

In [164]:
#Función 8: Mat
#Interpret the input as a matrix.

x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,1] = 6
m




matrix([[1, 6],
        [3, 4]])

In [165]:
#Función 9: identity
#Return the identity array.
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [166]:
#Función 10: asarray
#Convert the input to an array.
b = [10, 20]
np.asarray(b)


array([10, 20])

In [167]:
#Función 11: Copy
#Return an array copy of the given object.
x = np.array([1, 2, 3])
y = x
z = np.copy(x)

print(x)
print(z)

[1 2 3]
[1 2 3]


In [169]:
#Función 12: Linspace
#Return evenly spaced numbers over a specified interval.
#Returns num evenly spaced samples, calculated over the interval [start, stop].
#The endpoint of the interval can optionally be excluded.
np.linspace(0.0, 2.0, num=4)


array([0.        , 0.66666667, 1.33333333, 2.        ])

In [170]:
#Función 13: logspace
#Return numbers spaced evenly on a log scale.
#In linear space, the sequence starts at base ** start (base to the power of start) 
#and ends with base ** stop (see endpoint below).
np.logspace(1.0, 3.0, num=5, base=3.0)


array([ 3.        ,  5.19615242,  9.        , 15.58845727, 27.        ])

In [174]:
#Función 14: triu
#Upper triangle of an array.
print(np.triu([[10,20,30],[40,50,6],[70,80,90],[10,11,12]],1))
print(np.triu([[10,20,30],[40,50,6],[70,80,90],[10,11,12]],0))

[[ 0 20 30]
 [ 0  0  6]
 [ 0  0  0]
 [ 0  0  0]]
[[10 20 30]
 [ 0 50  6]
 [ 0  0 90]
 [ 0  0  0]]


In [204]:
#Función 15: Meshgrid
#Return coordinate matrices from coordinate vectors.
nx, ny = (5, 10)
x = np.linspace(0, 5, nx)
y = np.linspace(0, 5, ny)
xv, yv = np.meshgrid(x, y)
xv


array([[0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ]])

In [205]:
#Función 16: diagflat
#Create a two-dimensional array with the flattened input as a diagonal.
print(np.diagflat([[10,20], [30,40]]))
print(np.diagflat([11,22], 1))


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
[[ 0 11  0]
 [ 0  0 22]
 [ 0  0  0]]


In [206]:
#Función 17: geomspace
#Return numbers spaced evenly on a log scale (a geometric progression).
print(np.geomspace(1, 1000, num=4))
print(np.geomspace(1, 1000, num=4, endpoint=False))


[   1.   10.  100. 1000.]
[  1.           5.62341325  31.6227766  177.827941  ]


In [207]:
#Función 18: Full like
#Return a full array with the same shape and type as a given array.

a = np.arange(6, dtype=int)
print(a)
print(np.full_like(x, 1))


[0 1 2 3 4 5]
[1. 1. 1. 1. 1.]


#### Array manipulations routine

In [208]:
#Función 19: Shape
#Return the shape of an array.

np.shape(np.eye(5))

(5, 5)

In [211]:
#Función 20: Reshape
#Gives a new shape to an array without changing its data.
a = np.array([[10,20,30], [40,50,60]])
print(np.reshape(a, 6))
print(np.reshape(a, (3,-1)))       

[10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]


In [212]:
#Función 21: Ravel
#Return a contiguous flattened array.
b = np.array([[10, 20, 30], [40, 50, 60]])
np.ravel(b)
print(np.ravel(b))


[10 20 30 40 50 60]


In [214]:
#Función 22: ndarray.flat
a = np.arange(2, 8).reshape(2, 3)
a


array([[2, 3, 4],
       [5, 6, 7]])

In [215]:
#Función 23: ndarray.flatten
#Return a copy of the array collapsed into one dimension.
x = np.array([[10,20], [30,40]])
x.flatten()


array([10, 20, 30, 40])

In [218]:
#Función 24: Moveaxis
#Move axes of an array to new positions.
x = np.zeros((3, 4, 5))
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)


(4, 5, 3)
(5, 3, 4)


In [221]:
#Función 25: rollaxis
#Roll the specified axis backwards, until it lies in a given position.
a = np.ones((3,4,5,6))
print(a)
print(np.rollaxis(a, 3, 1).shape)
print(np.rollaxis(a, 2).shape)

[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1

In [223]:
#Función 26: ndarray.T
#The transposed array.
x = np.array([[10,20],[30,40]])
print(x)
print("La matriz es:")
print(x.T)

[[10 20]
 [30 40]]
La matriz transpuesta es:
[[10 30]
 [20 40]]


In [226]:
#Función 27: transpose
#Reverse or permute the axes of an array; returns the modified array.
x = np.arange(4,8).reshape((2,2))
print(x)
print("La matriz transpuesta es:")
print(np.transpose(x))


[[4 5]
 [6 7]]
La matriz transpuesta es:
[[4 6]
 [5 7]]


In [229]:
#Función 28: at least 1d
#Convert inputs to arrays with at least one dimension
print(np.atleast_1d(1.0))

x = np.arange(12.0).reshape(3,4)
print(x)
print("La matriz en una dimensión es:")
print(np.atleast_1d(x))

[1.]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
La matriz en una dimensión es:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [230]:
#Función 29: at least 2d
#View inputs as arrays with at least two dimensions.
print(np.atleast_2d(3.0))
x = np.arange(4)
print(x)
print("La matriz en dos dimensiones es:")
print(np.atleast_2d(x))


[[3.]]
[0 1 2 3]
La matriz en dos dimensiones es:
[[0 1 2 3]]


In [235]:
#Función 30: at least 3d
#View inputs as arrays with at least three dimensions.
print(np.atleast_3d(3.0))
x = np.arange(5)
print(x)
print("La matriz es:")
print(np.atleast_3d(x).shape)



[[[3.]]]
[0 1 2 3 4]
La matriz es:
(1, 5, 1)


In [242]:
#Función 31: Squeeze
#Remove single-dimensional entries from the shape of an array.
x = np.array([[[10], [11], [22]]])
print(x.shape)
print(np.squeeze(x).shape)
print(np.squeeze(x, axis=0).shape)


(1, 3, 1)
(3,)
(3, 1)


In [243]:
#Función 32: asscalar
#Convert an array of size 1 to its scalar equivalent.
np.asscalar(np.array([40]))


40

In [245]:
#Función 33: concatenate
#Join a sequence of arrays along an existing axis.
x = np.array([[10, 20], [30, 40]])
y = np.array([[50, 60]])
np.concatenate((x, y), axis=0)



array([[10, 20],
       [30, 40],
       [50, 60]])

In [247]:
#Función 34: Stack
#Join a sequence of arrays along a new axis.
x = np.array([10, 20, 30])
y = np.array([25, 35, 45])
z=np.stack((x, y))
print(z)
#aplicando ravel
print(np.ravel(z)) 

[[10 20 30]
 [25 35 45]]
[10 20 30 25 35 45]


In [248]:
#Función 35: Split 
#Split an array into multiple sub-arrays as views into ary.
a = np.arange(9)
np.split(a, 3)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [252]:
#Función 36: Array split
#Split an array into multiple sub-arrays.
b = np.arange(8)
np.array_split(b, 3)



[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [255]:
#Función 37: Delete
#Return a new array with sub-arrays along an axis deleted. 
#For a one dimensional array, this returns those entries not returned by arr[obj].
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(c)
print(np.delete(c, 1, 0))#Elimina el segundo array
print()
print(np.delete(c, 2, 0))#Elimina el último array
print()
print(np.delete(c, 0, 0))#Elimina el primer array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [256]:
#Función 38: Append
#Append values to the end of an array.
print(np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]))

print("Otra opción es: ")
print(np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0))


[1 2 3 4 5 6 7 8 9]
Otra opción es: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [260]:
#Función 39: rot90
#Rotate an array by 90 degrees in the plane specified by axes.
a = np.array([[10,20],[30,40]], int)
print(a)
print("Aplicando rot90 se obtiene: ")
print(np.rot90(a))
print("Otro ejemplo sería: ")
b = np.array([[10,20,30],[40,50,60]], int)
print(b)
print("Aplicando rot90 se obtiene: ")
print(np.rot90(b))

[[10 20]
 [30 40]]
Aplicando rot90 se obtiene: 
[[20 40]
 [10 30]]
Otro ejemplo sería: 
[[10 20 30]
 [40 50 60]]
Aplicando rot90 se obtiene: 
[[30 60]
 [20 50]
 [10 40]]


#### Binary operations

In [261]:
#Función 40: bitwise_and
#Compute the bit-wise AND of two arrays element-wise.
print(np.bitwise_and(13, 17))
print(np.binary_repr(12))

1
1100


In [264]:
#Función 41: Bitwise_or
#Compute the bit-wise OR of two arrays element-wise.
print(np.bitwise_or(15, 17))
print(np.bitwise_or(32, 2))
print(np.bitwise_or([33, 5], 1))

31
34
[33  5]


In [267]:
#Función 42: Invert
#Compute bit-wise inversion, or bit-wise NOT, element-wise.
x = np.invert(np.array(15, dtype=np.uint8))
print(x)
print(np.binary_repr(x, width=8))


240
11110000


In [269]:
#Función 43: Binary repr
#Return the binary representation of the input number as a string.
print(np.binary_repr(5))
print(np.binary_repr(-7))

101
-111


#### String Operations

In [272]:
#Función 44: Char add
#Return element-wise string concatenation for two arrays of str or unicode.
a=np.array(3)
b=np.array(5)
np.add(a,b)

8

In [273]:
#Función 45:Char Multiply
#Return (a * i), that is string multiple concatenation, element-wise.
a=np.array(3)
b=np.array(5)
np.multiply(a,b)

15

In [274]:
#Función 46: Char Mod
#Return (a % i), that is pre-Python 2.6 string formatting (interpolation), 
#element-wise for a pair of array_likes of str or unicode.
a=np.array(3)
b=np.array(5)
np.mod(a,b)

3

In [276]:
#Función 47: capitalize
#Return a copy of a with only the first character of each element capitalized.
a = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4')
print(a)
print("El proceso es:")
print(np.char.capitalize(a))


[b'a1b2' b'1b2a' b'b2a1' b'2a1b']
El proceso es:
[b'A1b2' b'1b2a' b'B2a1' b'2a1b']


In [283]:
#Función 48: Char Decode
#Calls str.decode element-wise.
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
print(np.char.encode(c, encoding='cp037'))



[b'\x81\xc1\x81\xc1\x81\xc1' b'@@\x81\xc1@@'
 b'\x81\x82\xc2\xc1\xc2\x82\x81']


In [284]:
#Función 49: Char Lower
#Return an array with the elements converted to lowercase
d = np.array(['HOLA', 'H1U2G3O', 'BCA1'])
print(np.char.lower(d))

['hola' 'h1u2g3o' 'bca1']


In [285]:
#Función 50: Char Lstrip
#For each element in a, return a copy with the leading characters removed.
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
print(np.char.lstrip(c, 'a'))

['AaAaA' '  aA  ' 'bBABba']


In [286]:
#Función 51: Swapcase
#Return element-wise a copy of the string with uppercase characters converted to lowercase and vice versa.
c=np.array(['a1B c','1b Ca','b Ca1','cA1b'],'S5')
print(np.char.swapcase(c))

[b'A1b C' b'1B cA' b'B cA1' b'Ca1B']


In [287]:
#Función 52: Char Title
#Return element-wise title cased version of string or unicode.
d=np.array(['a1b c','1b ca','b ca1','ca1b'],'S5')
print(np.char.title(c))

[b'A1B C' b'1B Ca' b'B Ca1' b'Ca1B']


In [289]:
#Función 53: Char Upper
#Return an array with the elements converted to uppercase.
a = np.array(["hola","soy","hugo"])
print(np.char.upper(a))

['HOLA' 'SOY' 'HUGO']


In [291]:
#Función 54: Char count
#Returns an array with the number of non-overlapping occurrences of substring sub in the range [start, end].
c = np.array(['Dulce', ' Hugo  ', 'uUuuU'])
print(np.char.count(c, 'u'))

[1 1 3]


In [292]:
#Función 55: Endswith
#Returns a boolean array which is True where the string element in a ends with suffix, otherwise False.
a = np.array(['correr', 'volar'])
print(np.char.endswith(a, 'ar'))


[False  True]


#### Más sobre Array manipulations routines

In [293]:
#Función 56: Roll
#Roll array elements along a given axis.
y = np.arange(12)
print(np.roll(y, 2))


[10 11  0  1  2  3  4  5  6  7  8  9]


In [294]:
#Función 57: Reshape
x = np.array([[10,20,30], [40,50,60]])
print(np.reshape(x, 6))
print(np.reshape(x, (3,-1)))


[10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]


In [298]:
#Función 58: Flip
#Reverse the order of elements in an array along the given axis.
x = np.arange(8).reshape((2,2,2))
print(x)
print("Con flip en 0")
print(np.flip(x, 0))
print("Con flip en 1")
print(np.flip(x, 1))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Con flip en 0
[[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]
Con flip en 1
[[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]


In [300]:
#Función 59: fliplr
x = np.diag([4,5,6])
print(x)
print("Con el procedimiento queda de la siguiente manera:")
print(np.fliplr(x))


[[4 0 0]
 [0 5 0]
 [0 0 6]]
Con el procedimiento queda de la siguiente manera:
[[0 0 4]
 [0 5 0]
 [6 0 0]]


In [302]:
#Función 60: flipud
#Flip the entries in each column in the up/down direction. 
#Rows are preserved, but appear in a different order than before.
z = np.diag([1, 2, 3])
print(z)
print("El procedimiento da como resultado:")
print(np.flipud(z))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
El procedimiento da como resultado:
[[0 0 3]
 [0 2 0]
 [1 0 0]]


In [303]:
#Función 61: Resize
#Return a new array with the specified shape.
x=np.array([[10,11],[20,32]])
np.resize(x,(2,3))


array([[10, 11, 20],
       [32, 10, 11]])

In [304]:
#Función 62: trim zeros
#Trim the leading and/or trailing zeros from a 1-D array or sequence.
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
print(np.trim_zeros(a)) #Elimina los elementos 0
print(np.trim_zeros(a, 'b'))#Elimina los caracteres b, pero como no hay deja igual a "a"

[1 2 3 0 2 1]
[0 0 0 1 2 3 0 2 1]


In [305]:
#Función 63: Unique
#Find the unique elements of an array.
np.unique([10, 11, 20, 20, 20, 20 , 10, 33, 33])


array([10, 11, 20, 33])

In [306]:
#Función 64: Tile
#Construct an array by repeating A the number of times given by reps.
x =np.array([10,20,30])
print("Con dos repeticiones queda:")
print(np.tile(a, 2))
print("Con cinco repeticiones queda:")
print(np.tile(a,5))

Con dos repeticiones queda:
[0 0 0 1 2 3 0 2 1 0 0 0 0 1 2 3 0 2 1 0]
Con cinco repeticiones queda:
[0 0 0 1 2 3 0 2 1 0 0 0 0 1 2 3 0 2 1 0 0 0 0 1 2 3 0 2 1 0 0 0 0 1 2 3 0
 2 1 0 0 0 0 1 2 3 0 2 1 0]


In [308]:
#Función 65: Repeat
#Repeat elements of an array.
print(np.repeat(3, 4))
print(np.repeat(5,5))
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))


[3 3 3 3]
[5 5 5 5 5]
[1 1 2 2 3 3 4 4]


In [310]:
#Función 66: dsplit
#Split array into multiple sub-arrays along the 3rd axis (depth).
a= np.arange(16)
print(a)
b = np.arange(16).reshape(2,2,4)
print(b)
print("El procedimiento queda de la siguiente manera: ")
print(np.dsplit(b, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
El procedimiento queda de la siguiente manera: 
[array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]]]), array([[[ 2,  3],
        [ 6,  7]],

       [[10, 11],
        [14, 15]]])]


In [312]:
#Función 67: hsplit
#Split an array into multiple sub-arrays horizontally (column-wise).
a= np.arange(16)
print(a)
b = np.arange(16).reshape(2,2,4)
print(b)
print("El procedimiento queda de la siguiente manera: ")
print(np.hsplit(b, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
El procedimiento queda de la siguiente manera: 
[array([[[ 0,  1,  2,  3]],

       [[ 8,  9, 10, 11]]]), array([[[ 4,  5,  6,  7]],

       [[12, 13, 14, 15]]])]


In [313]:
#Función 68: vsplit
#Split an array into multiple sub-arrays vertically (row-wise).
a= np.arange(16)
print(a)
b = np.arange(16).reshape(2,2,4)
print(b)
print("El procedimiento queda de la siguiente manera: ")
print(np.vsplit(b, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
El procedimiento queda de la siguiente manera: 
[array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]]), array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])]


In [314]:
#Función 69: Column_stack
#Stack 1-D arrays as columns into a 2-D array.
x = np.array((1,2,3))
y = np.array((4,5,6))
print(np.column_stack((x,y)))


[[1 4]
 [2 5]
 [3 6]]


In [316]:
#Función 70: dstack
#Stack arrays in sequence depth wise (along third axis).
x = np.array((1,2,3,4))
y = np.array((4,5,6,7))
print(np.dstack((x,y)))

[[[1 4]
  [2 5]
  [3 6]
  [4 7]]]


In [317]:
#Función 71: hstack
#Stack arrays in sequence horizontally (column wise).
x = np.array((1,2,3,4,5))
y = np.array((4,5,6,7,8))
print(np.hstack((x,y)))

[1 2 3 4 5 4 5 6 7 8]


In [318]:
#Función 72: vstack
#Stack arrays in sequence vertically (row wise).
x = np.array((1,2,3,4,5))
y = np.array((4,5,6,7,8))
print(np.vstack((x,y)))

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [330]:
#Función 73: Block
#Assemble an nd-array from nested lists of blocks.
a = np.array([10, 20, 30])
b = np.array([20, 30, 40])
print(np.block([a, b, 10]))   

x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print(np.block([[x], [y]]))         

[10 20 30 20 30 40 10]
[[1 2 3]
 [2 3 4]]


## Tarea, inciso 2
***


2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    

    


In [346]:
#Save de NPY
Libreria = TemporaryFile()
a = np.arange(15)
np.save(Libreria, a)
_ = Libreria.seek(0)
np.load(Libreria)



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [350]:
with open('test.npy', 'wb') as f:
    np.save(f, np.array([10, 20]))
    np.save(f, np.array([11, 333]))
with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a, b)


[10 20] [ 11 333]


In [351]:
#Ejemplo con NPZ
from tempfile import TemporaryFile
outfile = TemporaryFile()
a = np.arange(8)
b = np.sum(a)

np.savez(outfile, a, b)
_ = outfile.seek(0)#No permite abrir información que sea falsa.
npzfile = np.load(outfile)
npzfile.files #Guarda el contenido en dos archivos
print("El archivo 0 es: ")
print(npzfile['arr_0'])#Abre el archivo 0, el cual corresponde a "a"
print("El archivo 1 es: ")
print(npzfile['arr_1'])#Abre el archivo 1, el cual corresponde a "b"


El archivo 0 es: 
[0 1 2 3 4 5 6 7]
El archivo 1 es: 
28


In [373]:
a = np.random.random((5,5))
b = np.arange(1,15,3)

np.savez('arreglos.bin', objA = a, objB = b)

In [374]:
# Lee un diccionario del archivo npz
d = np.load('arreglos.bin.npz')

In [375]:
d['objA']

array([[0.0812315 , 0.43541098, 0.04344687, 0.094602  , 0.55394225],
       [0.55616373, 0.11018304, 0.09320869, 0.46411176, 0.94321404],
       [0.38483226, 0.89753601, 0.68778361, 0.0928998 , 0.51664688],
       [0.02802739, 0.92494211, 0.74116116, 0.88353496, 0.42758144],
       [0.59779086, 0.66082568, 0.6691505 , 0.91410457, 0.96348612]])

In [376]:
d['objB']

array([ 1,  4,  7, 10, 13])

## Tarea inciso 3
***

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    

In [377]:
#Comando para guardar 
a = np.arange(1,15,3)
b = np.random.random((5,5))
np.savetxt('test.out', b, delimiter=',')#La coma es la que hace la separación como columna. 
np.savetxt('testa.out', a)


In [372]:
#Comando para abrir
np.loadtxt('test.out', delimiter=',') #El delimitador que en este caso es ",", hace que la coma sea el separador entre
#columnas.

array([[0.304414  , 0.09324746, 0.30127232, 0.49776218, 0.59563951],
       [0.47868127, 0.57336027, 0.83268132, 0.70537174, 0.60293253],
       [0.20156857, 0.88283943, 0.02486906, 0.83733593, 0.54879307],
       [0.25139638, 0.60912507, 0.36559213, 0.32919736, 0.56474539],
       [0.40672344, 0.14882626, 0.91355127, 0.99554564, 0.42725966]])

In [378]:
np.loadtxt('testa.out')

array([ 1.,  4.,  7., 10., 13.])

## Tarea inciso 4
***
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [405]:
def estimacionMCO(x):
    ini= np.loadtxt('regresion.CSV', delimiter=',') #Es importante indicar que dicho archivo de texto puede tener
    #una cantidad ilimitada de filas, pero por fuerza debe tener 7 columnas.
    print("La matriz a analizar es: ")
    print(ini)
    x=ini[::,:6] #Selecciona las primeras 6 columnas de la matriz que contiene los datos de la regresión
    igu=ini[::,6]#Selecciona la última columna de la regresión (igualdades), pero las regresa como fila
    y=igu[:,None]#Convierte en columna los valores de "y"
    xt=x.T #Proporciona la matriz transpuesta de "x"
    xTx=xt@x #Realiza la operación de matriz transpuesta de "x"  por la matriz de "x"
    betas=np.linalg.inv(xTx)@xt@y #Devuelve los betas de la regresión lineal
    resultado_y=x@betas
    print("Los betas de la regresión son: ")
    print(betas)
    print("La comprobación de y es: ")
    print(resultado_y)
    

In [407]:
#Genera una matriz aleatoria de 7*7 y automaticamente guarda un archivo en formato "csv"
reg = np.random.randint(20,size=[8,7])   
np.savetxt('regresion.CSV', reg, delimiter=',')

In [417]:
estimacionMCO(x) #Ejecuta la función de regresión lineal

La matriz a analizar es: 
[[16.  0.  4. 18.  9.  1. 15.]
 [ 9.  1. 16.  2. 11.  5. 15.]
 [15. 16. 12.  3.  1. 10. 10.]
 [14.  3.  1.  0.  7.  6. 11.]
 [11.  2.  1.  6. 10.  4. 10.]
 [ 9.  7.  6. 19.  0.  4. 16.]
 [ 8.  6.  3.  2. 17.  9.  1.]
 [16. 12.  5.  9. 16. 16.  6.]]
Los betas de la regresión son: 
[[ 0.8495043 ]
 [-0.87500104]
 [ 0.6350389 ]
 [ 0.31546237]
 [-0.45352566]
 [ 0.39713669]]
La comprobación de y es: 
[[18.12595274]
 [14.55898596]
 [10.82724299]
 [ 9.11123645]
 [ 7.17564845]
 [12.91309658]
 [-0.05363645]
 [ 8.20418855]]


##### Resumen de operaciones para hacer una regresión lineal

In [380]:
#Genera una matriz aleatoria de 7*7 y automaticamente guarda un archivo en formato "csv"
reg = np.random.randint(20,size=[7,7])   
np.savetxt('regresion.CSV', reg, delimiter=',')

In [408]:
ini= np.loadtxt('regresion.CSV', delimiter=',')
ini#Se define a una variable que automáticamente abre un archivo csv con los datos de la matriz aleatoria.

array([[16.,  0.,  4., 18.,  9.,  1., 15.],
       [ 9.,  1., 16.,  2., 11.,  5., 15.],
       [15., 16., 12.,  3.,  1., 10., 10.],
       [14.,  3.,  1.,  0.,  7.,  6., 11.],
       [11.,  2.,  1.,  6., 10.,  4., 10.],
       [ 9.,  7.,  6., 19.,  0.,  4., 16.],
       [ 8.,  6.,  3.,  2., 17.,  9.,  1.],
       [16., 12.,  5.,  9., 16., 16.,  6.]])

In [409]:
mat_x=ini[::,:6]#Crea la variable "matriz x", la cual contiene las primeras 6 columnas de la regresión
#la cual corresponde a las diversas variables "x"
mat_x

array([[16.,  0.,  4., 18.,  9.,  1.],
       [ 9.,  1., 16.,  2., 11.,  5.],
       [15., 16., 12.,  3.,  1., 10.],
       [14.,  3.,  1.,  0.,  7.,  6.],
       [11.,  2.,  1.,  6., 10.,  4.],
       [ 9.,  7.,  6., 19.,  0.,  4.],
       [ 8.,  6.,  3.,  2., 17.,  9.],
       [16., 12.,  5.,  9., 16., 16.]])

In [410]:
mat_y=ini[::,6]#Crea la variable "matriz y", la cual contiene la última columna, pero con el defecto de que la regresa
#en forma de fila.
mat_y

array([15., 15., 10., 11., 10., 16.,  1.,  6.])

In [411]:
mat_y_col=mat_y[:,None] #La variable "matriz y columna", como su nombre lo indica hace que "matriz y" se
#represente en forma de fila
mat_y_col

array([[15.],
       [15.],
       [10.],
       [11.],
       [10.],
       [16.],
       [ 1.],
       [ 6.]])

In [413]:
mat_x_trans=mat_x.T #Variable que obtiene la matriz transpuesta de x
mat_x_trans

array([[16.,  9., 15., 14., 11.,  9.,  8., 16.],
       [ 0.,  1., 16.,  3.,  2.,  7.,  6., 12.],
       [ 4., 16., 12.,  1.,  1.,  6.,  3.,  5.],
       [18.,  2.,  3.,  0.,  6., 19.,  2.,  9.],
       [ 9., 11.,  1.,  7., 10.,  0., 17., 16.],
       [ 1.,  5., 10.,  6.,  4.,  4.,  9., 16.]])

In [414]:
XTX=mat_x_trans@mat_x #Realiza la operación de matriz transpuesta de x por la matriz x
XTX

array([[1280.,  616.,  571.,  748.,  858.,  703.],
       [ 616.,  499.,  333.,  315.,  362.,  465.],
       [ 571.,  333.,  488.,  311.,  372.,  345.],
       [ 748.,  315.,  311.,  819.,  425.,  320.],
       [ 858.,  362.,  372.,  425.,  897.,  565.],
       [ 703.,  465.,  345.,  320.,  565.,  531.]])

In [415]:
beta=np.linalg.inv(XTX)@mat_x_trans@mat_y_col
beta #Realiza la operación de econometría en la cual se obtienen los valores de los betas
#Donde los betas son iguales a la multiplicación entre:
#(Inversa de transpuesta de x * matriz de x)*(transpuesta de x)*(Columna de la matriz y)

array([[ 0.8495043 ],
       [-0.87500104],
       [ 0.6350389 ],
       [ 0.31546237],
       [-0.45352566],
       [ 0.39713669]])

In [416]:
Res_y=mat_x@beta
Res_y #Genera los valores de y de acuerdo a la regresión realizada

array([[18.12595274],
       [14.55898596],
       [10.82724299],
       [ 9.11123645],
       [ 7.17564845],
       [12.91309658],
       [-0.05363645],
       [ 8.20418855]])